USE aadb;

DROP TABLE IF EXISTS biedingen;
DROP TABLE IF EXISTS klus;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS person;

CREATE TABLE person (
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    VOORNAAM VARCHAR(50),
    ACHTERNAAM VARCHAR(50),
    FUNCTIE VARCHAR(50) NOT NULL,
    ENABLED BOOLEAN,

    PRIMARY KEY(USERNAME)
);

CREATE TABLE authorities (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    AUTH VARCHAR(50) NOT NULL,
    
    PRIMARY KEY(ID),
    FOREIGN KEY (USERNAME) REFERENCES person (USERNAME)
    
);

CREATE TABLE klus (
    KLUS_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    KLANT_USERNAME VARCHAR(50)NOT NULL,
    PRIJS INT NOT NULL,
    BESCHRIJVING VARCHAR(255),
    STATUS ENUM('BESCHIKBAAR', 'GEBODEN', 'TOEGEWEZEN', 'UITGEVOERD', 'BEOORDEELD') NOT NULL,
    KLUSJESMAN_USERNAME VARCHAR(50),
    RATING INT,

    PRIMARY KEY (KLUS_ID),
    FOREIGN KEY (KLANT_USERNAME) REFERENCES person (USERNAME),
    FOREIGN KEY (KLUSJESMAN_USERNAME) REFERENCES person (USERNAME)
    
);

CREATE TABLE biedingen (
    ID INT AUTO_INCREMENT,
    KLUSJESMAN_USERNAME VARCHAR(50) NOT NULL,
    KLUS_ID INT NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY (KLUS_ID) REFERENCES klus (KLUS_ID),
    FOREIGN KEY (KLUSJESMAN_USERNAME) REFERENCES person (USERNAME)
);

-- Inserting sample data
INSERT INTO person (USERNAME, PASSWORD, VOORNAAM, ACHTERNAAM,FUNCTIE,ENABLED) 
VALUES 
    ('stijn', '$2a$12$uOOvNz00aXAzcIzWnfMzd.g1P2n6pof./QTSG4Kh8tijxjFsAQnTK', 'Stijn', 'Is cool', 'KLUSJESMAN', '1'),
    ('thijs', '$2a$12$MdFFQSIRvDEiqNcWi3ebXu0qLVs950ZhUFXy4dm9h4.d2gPoGNu36', 'Stijn', 'Is cool', 'KLANT', '1');

INSERT INTO klus (NAME, KLANT_USERNAME, PRIJS, BESCHRIJVING, STATUS)
VALUES 
    ('knuffel komen geven','thijs', 0, 'ZEER DRINGEND!', 'GEBODEN'),
    ('kusje komen geven','thijs', 0, 'ZEER DRINGEND!', 'BESCHIKBAAR');
    
INSERT INTO klus (NAME, KLANT_USERNAME, PRIJS, BESCHRIJVING, STATUS, KLUSJESMAN_USERNAME)
VALUES 
    ('thijs helpen','thijs', 0, 'niet al te dringend', 'UITGEVOERD', 'stijn');

INSERT INTO biedingen (KLUS_ID, KLUSJESMAN_USERNAME)
VALUES 
    ((SELECT KLUS_ID FROM klus WHERE NAME = 'knuffel komen geven'), 'stijn');

INSERT INTO authorities (USERNAME, AUTH) 
VALUES 
    ('stijn', 'ADMIN'),
    ('thijs', 'USER'),
    ('stijn', 'KLUSJESMAN'),
    ('thijs', 'KLANT');

