USE aadb;

DROP TABLE IF EXISTS biedingen;
DROP TABLE IF EXISTS klus;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS person;

CREATE TABLE person (
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    VOORNAAM VARCHAR(50),
    ACHTERNAAM VARCHAR(50),
    FUNCTIE VARCHAR(50) NOT NULL,
    ENABLED BOOLEAN,

    PRIMARY KEY(USERNAME)
);

CREATE TABLE authorities (
    USERNAME VARCHAR(50) NOT NULL,
    AUTH VARCHAR(50) NOT NULL,
    
    PRIMARY KEY(USERNAME,AUTH),
    FOREIGN KEY (USERNAME) REFERENCES person (USERNAME)
    
);

CREATE TABLE klus (
    KLUS_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    KLANT_USERNAME VARCHAR(50)NOT NULL,
    PRIJS INT NOT NULL,
    BESCHRIJVING VARCHAR(255),
    STATUS ENUM('BESCHIKBAAR', 'GEBODEN', 'TOEGEWEZEN', 'UITGEVOERD', 'BEOORDEELD') NOT NULL,
    KLUSJESMAN_USERNAME VARCHAR(50),
    RATING INT,

    PRIMARY KEY (KLUS_ID),
    FOREIGN KEY (KLANT_USERNAME) REFERENCES person (USERNAME),
    FOREIGN KEY (KLUSJESMAN_USERNAME) REFERENCES person (USERNAME)
    
);

CREATE TABLE biedingen (
    KLUSJESMAN_USERNAME VARCHAR(50) NOT NULL,
    KLUS_ID INT NOT NULL,

    FOREIGN KEY (KLUS_ID) REFERENCES klus (KLUS_ID),
    FOREIGN KEY (KLUSJESMAN_USERNAME) REFERENCES person (USERNAME)
);

INSERT INTO person (USERNAME, PASSWORD, VOORNAAM, ACHTERNAAM,FUNCTIE,ENABLED) VALUES ('stijn', 'cool', 'Stijn', 'Is cool','KLUSJESMAN','1');
INSERT INTO person (USERNAME, PASSWORD, VOORNAAM, ACHTERNAAM,FUNCTIE,ENABLED) VALUES ('thijs', 'leuk', 'Stijn', 'Is cool','KLANT','1');

INSERT INTO klus (NAME, KLANT_USERNAME, PRIJS, BESCHRIJVING, STATUS)
VALUES ('knuffel komen geven','thijs' , 0, 'ZEER DRINGEND!', 'GEBODEN');

INSERT INTO klus (NAME, KLANT_USERNAME, PRIJS, BESCHRIJVING, STATUS)
VALUES ('kusje komen geven','thijs' , 0, 'ZEER DRINGEND!', 'BESCHIKBAAR');

INSERT INTO biedingen (KLUS_ID, KLUSJESMAN_USERNAME)
VALUES ((SELECT KLUS_ID FROM klus WHERE NAME = 'knuffel komen geven'),'stijn');

INSERT INTO authorities (USERNAME,AUTH) VALUES ('stijn','ADMIN');
INSERT INTO authorities (USERNAME,AUTH) VALUES ('thijs','USER');




